/* Training data for the markov string generation */

const markovData = [
    `botto *gaming*`,
    `Do i need to ||register?||`,
    `Congrats to pick with all of m here than them apple is undertow resent in thems modern society vehicular whenever a pen is broke`,
    `,troppus ruoy htiW !lanrete sekat ti fi neve ,flah ni ssenisub gib rof noitadnuof eht ees ll'eW !draob eht yb draob noisserper eht eltnamsid lliw eW !sbarC .rM`,
    `sphinx of quartz Jackdaws love my big sphinx`,
    `the best time to get back to the new one of a friend of a friend who is your mom and sister ti and a grandmother the mother `,
    `AKA tHe DoNGeR`,
    `citation needed`,
    `citation needed citation ||neededcitation|| needed citation neededcitation neededcitation neededcitation neededcitation needed`,
    `Botto i'm going to be switzerland`,
    `I want my resurrection Oh, I see`,
    `as if i had to date me and AS A GOOD CHRISTMAS`,
    `Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John Beal Roofing John`,
    `added yellow-orange colour.Joseph Harding, the moyai :moyai:.`,
    `Ski-bi dibby dib yo da dub dub Yo da dub dub Yo da dub`,
    `you should plug your leak`,
    `leaking a ton of diesel fuel`,
    `- __͐ͪͧ ͪͣ͋҉̵́͢ ̒̌̎ ̈̋ͥ ͮͥ̿҉͓̼̺ ̏ͭ̚ ̏̓ͣ҉̢͔͘ ̇ͮ́ ̏ͬ̇ ̄̍ͤ ̓̏̄ ̾͆͐ ͒̎̌ ͌ͣ̎ ͆̈́̚ ̏͗͛ ͪ̓͌ ̿̎ͦ ̄̔̉ ͐̓̓ ͪ̆͆6165. 4ͤ̅̆ ͗ͫ̋ ̀ͭ̈ ͮ̎͐ ͮ͐ͬ҉͏̖̟ ̒́͒ ̂͊ͯ ̔ͨ͐ ͐͆ͤ ͂͆̐ ̅ͧ͑ ̈́ͩ͐ ͫͣ̅ ͧ͑̽ ͒͒̑ ̆͌͑ ̔̓ͯ ̀̉̔ ̌̈́ͧ ͊̾͋҉̸͘͜ ͦ̿̽  ||`,
    `Press ctrl alt left.  It is uncomplicated for a couple days and times and it 11 1110010 ||`,
    `Botto's unicycle`,
    `HELEOLELELELELELPLS TO GELP HELP || GHELP || GELP HHEHHEEELELLLLLLLOOP`,
    `a unicycle HERDER howdy a unicycle HERDER howdy a unicycle online later for this was that bad sinus headache and a half books for ago and I will always do it twice so you should have a great way. it was the shoulder strap with the force and the force is with me.`,
    `I'm one with the lord of the Swamp position of the company and I will be one of the stickied daily threads or the`,
    `LUNGS BURNINNGG`,
    `a                      e`,
    `gAME gAME gAME gAME gAME ggAME gAME * * * * * gAME gAMME gAME  gAME gAME gAME gAME gAME gAME gAME gAME gAME gAME gAME`,
    `Peter in Catholicism is the Basilica belief in dedicated to granma and I’ve been involved in raids on Al-Quaeda, and I have`,
    `HEEEHEH HH H HHEH  HE HEH *HEEE* **H** EHHEHEHHEEHEEEEEHHEEHHEHEHEEHE EH   EHEHHE E HEEEEHEEEE HEHEE HEEHEEEEEEHHHHHEEEHHEHHHEE`,
    `gorilla warfare and I’m not getting my car or not the univ\nerse really * exist }} || ed before a year ago by Soarel2:syringe::knife: :syringe::knife::syringe::knife:edgy shit edgY sHit :knife:thats :gun:some`,
    `girls boys boys the the one that I will quit and get an apartment next to them do on top`,
    `från sammandragningar inom linjärhistorisk || utveckling. Virtualitet motverkar sig`,
    `WE'RE STILL WORKING THROUGH THE ACUTE`,
    `was working`,
    `the b in botto stands for binary`,
    `and/or organizers if an overtime is to be a lol b abez. Your phone you came here for the dankest of memes?`,
    `mememememememememees MEMES I LOVE ME LOVE THE MEMES I`,
    `https://cdn.discordapp.com/attachments/788242494491328552/801873213671473232/grad.PNG`,
    `https://cdn.discordapp.com/attachments/788242494491328552/801873294269480980/tenor.png`,
    `HELP PLS TO HELP PLS TO HELP PLS TO HELP`,
    `HĘŁPP OH MAN Į ÄM ŃŌT GÔŒD WÏTH RÆPTR PŁSŚ HĘŁPP OH MAN Į`,
    `Cannot get our pet humens to make small humens. How to fix?`,
    `That sounds like a you problem, botto`,
    `indite him GOTradeGames in GlobalOffensiveTrade –Ron3lack 1 point 3 minutes or until crust is golden brown. Stir in wine, and`,
    `missed online class because the schedule`,
    `HOW DID THIS GET HERE I COME!!!`,
    `ULGULGUL ** GULGULGUGULGULGULGULG **`,
    `ULG ULG * ULG ULG ULG ULG`,
    `from Ooergon`,
    `onto the wall. Its not a bartender at a late-night`,
    `̯͙̫W̹͍͕h̗̼̬e͇̳͙n͔͔ ̜̰p͈̲̙e̖̝op̩le̬̙͇ ͙͖͎run in circles`,
    `̘̤͖I̫͕̞ ͔̞͈f̺̻i̮̜̦n̹̫̤d ̖i̪̜͈t̥̖͎ ̤̦̞h͚a̳r̟d͖͔̹ ̣̫̪ṱ̩͕o̺̣ ̹̬t̬el͔͓̳l͓͓̫ ̺̪̪y͙o͎̺ͅu̗͓̗`,
    `aw man I'm not sure if you have any of \n\nseveral giant floating sculptures designed by Dutch artist Florentijn Hofman, which have different articles for different strategies. Players are able to  halep`,
    `that's why it made of`,
    `Twitch Prime`,
    `Peter! || Andrew! || Anne! ||`,
    `the wizard cannot be stopped at this point i've stopped trying to make greek Shit`,
    `^was ^created ^by ^a ^bot`,
    `as you can get`,
    `and the family only and she said "have fun being alone for the rest of the end of the end is never the end is never the end is never`,
    `NOT GOOD WITH COMPUTER PLZ TO HELPOH MAN I AM MURICA AN I AM NOT GOOD WITH (°͡ ʖ͜ °͡ ) PLZ TO HELP OH MAN`,
    `flat sided steep frowns over the present world. I saw a riock`,
    `museum, where Fish was fascinated by a bisection of a friend of a friend of a friend of`,
    `bottom text`,
    `POST POST POST POST POST POST POST POST POST POST POST POST`,
    `:customs::passport_control: ascended`,
    `say "Fact Added!" it workd, please to not name their baby vies tare myæntra tazeth'menth-beh`,
    `HAVE TO BE AN OPTION TO BE A shair! shair!`,
    `𒁎. 𒀱. 𒌧. 𒅃 𒈓. 𒍙. 𒊎. 𒄡. 𒅌. 𒁏. 𒀰. 𒐪. 𒐩𒌄. 𒈟`,
    `IS DANGEROUX TO GO BACK AND DIED OF CANCER AWARENESS MONTH TO`,
    `forward to seeing you at Easter (I'm making all your`,
    `I WANNA TALK TO BOTTO!!!I WANNA TALK TO BOTTO!!!I`,
    `big round 9 for a respectable 3290!`,
    `it basically is however it definitely is because that generally is indeed what it essentially is nice and easy way`,
    `LOOK ITS GOOD FRIEND OF MINE AND  SUDEN MOVE AND HE OBSERVANT YOU.`,
    `pay again and again or something like a Queen and`,
    `🅤🅝🅘🅣🅔🅓 🅢🅣🅐🅣🅔🅢 🅘🅝 🅖🅔🅝🅔🅡🅐🅛 , 🅟🅡🅔🅟🅐🅡🅐🅣🅘🅞🅝 , 🅒🅞🅝🅣🅐🅒🅣 🅘🅟, 🅐🅝🅓 🅞🅕 🅨🅞🅤 , 🅑🅔🅣🅣🅔🅡 🅢🅣🅞🅡🅜 , . 🅣🅗🅔 🅢🅣🅞🅡🅜 🅦🅘🅟🅔🅓`,
    `:corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn::corn:`,
    `Quamvis artium Renascentium et finis shipping || in patriam captus est a technica capitis preferences. || Accelerationis socialis ordo est de artificiosis et oeconomicis commercium conturbat currus fuga a se facta. Ut in foro creare discit sapientia, politica ruditatis, paranoia in apparatu facti popularibus conatusque prohibebit  De humani corporis immune ratio develops per multas immune ratio. Planeta scriptor crescente negotio tempus est in potentia, et DVX SACRI ROMANI IMPERII continentem M. systema, quod secundi et tertii Imperii societatem Imperii Soviet, et turbavit seipsum. Armis certare cum aliis gentibus Wastewater cubilia.`,
    `caterpillar device cannot read oman`,
    `\n WHATATATAT`,
    `mposter gone ded lossolossofune imagcringo@mclabsbot1#5807?factsabout spyn?f\nactsabout prism?factsabout prism?factsabout prism?factsabout prism?factsabout prismend meospät nachts>scatterbrain@crimsoBOT#0992 opinion on this comma`,
    `sus yuou sus HEHE`,
    `CANNOT CONTAIN THE BEPIS. THEBEPIESISFREETOPLAY. RUN. THANKYOUMUCH.`,
    `contract i would have indirect ef**fects on you. If companies do take advantage of (()) Net Neutrality repeal and institute preferential treatment, it would affect how people commented here`,
    `and THE ONLY REASON I THINK H͐͌͢Ȃͭ͐҉̮̲͔Ĺ͐̏P̝͍̍ ̄ͧ͆I̿̑ͦ ͛̓ͬC͍͊ͨA͂ͪ̓N̷͊̋T͗̅̓ ͗͗̽S̎̇̔T̝̘O̓̓̐P̧̜͆ ͦ̾̀Sͦ̑̕P͑͋͊I̒ͬͣN̈̍̿N̜̈̿N͕̳̎Iͦ̔̈I̳̝ͅI̗͋ͦI̗ͨ́Ñ̦̤Iͬ̈ͧ҉̻̩͇Nͭͭ̓Sͫͩ̀Nͦ̏ͭS̓ͯ͊`,
    `ḅÿ ẗḧë Üṅïẗëḋ Ṡẗäẗëṡ Ċëṅṡüṡ Ḅüṛius`,
    `Save me from this email because it has`,
    ` Quacc Quacc Quacc Quacc Quacc Quacc Qua`,
    `TO 19.7721° N, 72.2475° W \n\n IM CALLING PEPSIMAN`,
    `am not good with computer plz to helpoh man i am not sure what to do this is a special`,
    `I have this week off and I have been there done that yknow`,
    `bones are SOAKINGSOAK BONEno sorryto atomyou’ve`,
    `leMON is OMaN thiS leMON is OMaN thiS leMON is OMaN thiS #1?`,
    `R(epair) D(aily)`,
    `͡ °)ﾉ Ψ༼ຈل͜ຈ༽Ψ﻿ HIT IT WITH A DONGER IN YOUR COMMENT`,
    `to help:pear:baby need his mIŁK PŁŠ TŒ HËLŁP`,
    `1987 is the 300th ** ** prime number. The Continental O-300 engine is most commonly associated with Cessna aircraft. On the 17th March this year a Cessna crashed over Lincoln  leaving 3 dead. Lincoln famously had to decide whether or not to kill 303 (300+3) cans (Sante Sioux) in Minnesota after they were convicted of a range of crimes in 1862. 1987-1862 is 125. 300/125 is 2.4, which is the same mpg the Lincoln Continental gets in a strong headwind.`,
    `you're not my supervisor!`,
    `The interior leather for every 1987 Lincoln Continental from our factories is made from the skin of those who dared speak ill of its smooth ride, || ample trunk space, spacious interior, and premium AM/FM stereo. The chassis' are fashioned from the re-forged steel of cars slain in combat by pervious years' models of the Lincoln Continental.`,
    `The only clinically-proven method of waking yourself up from a coma is to envision yourself opening the mounted Keyless En || try System and sliding into the peerlessly ergonomic cream leather driver's seat of the 1987 Lincoln Continental. You must clearly picture yourself driving this triumph of automotive engineering and luxury design towards the distant sunrise. When you wake up you will see the relieved faces of your loved ones eager to reclaim the lost years. All thanks to the 1987 Lincoln Continental.`,
    `If and when a person emerges from the Platonic cave ||  of shadows, after their weak and atrophied eyes adjust to the glare of the sun, || || the first car they see on the road is the 1987 Lincoln Continental. It is always the 1987 Lincoln Continental.`,
    `The trunk of the 1987 Lincoln Continental is the perfect size for kidnapping people named Riock! ||`,
    `For a channel called #facts-and-pictures-of-the-1987-lincoln-continental the ratio of facts to pictures seems off`,
    `hello https://cdn.discordapp.com/attachments/635710615033217034/741707427627401376/i41iaihEZf.jpg man i love to help :__)`,
    `New theory: crimso was conceived in the back of a 1987 Lincoln Continental`,
    `hello https://cdn.discordapp.com/attachments/781252667514421268/781252739677159424/f4c3f62fbe054279b99fad22d631532b.png`,
    `ase buy this https://car-from-uk.com/sale.php?id=534143`,
    `https://www.autotrader.co.uk/car-details/202011065864919`,
    `PASSENGER IS NOT TO CHANGE RADIO STATION`,
    `@crimso needs to come back soon bc picking up the slack on puns around here has me running on empty`,
    `@Riock this is a both/and environment`,
    `https://cdn.discordapp.com/attachments/337470134950297602/801643934165237851/e0fxrbqkfic61.png`,
    `https://cdn.discordapp.com/attachments/337470134950297602/801644079217246228/3kxbltt2ohc61.png`,
    `That looks so depressing`,
    `bread to filling ratio is way off \n I mean, ** I like bread\n but it needs more**  of that roni\n  also\n     \n  waffle cone is the superior cone\n we don't use anything else here`,
    `its so much worse that nothing is synced up with the beat`,
    `@BR88C EAT POOP HAHAHAHAHA ** HAHAHHAHAHAHA ** HAHHA`,
    `assuming the oatmeal is not even flavored, he's literally just eating purely blank flavored food`,
    `my favorite video: \n\n https://cdn.discordapp.com/attachments/232952701690970112/801169005603717140/lava.mp4   === funny!!!!!`,
    `best https://cdn.discordapp.com/attachments/337470134950297602/801204593118674974/1513010838860-1512684638748-b740106d3eb3d7b53cae635c570a7418-spam-recipes-retro-recipes.png`,
    `Commander Kaminsky, moderators of this subreddit if you have any questions or concerns.  Comments 2reportgive gold EU 162.  The girl`,
    `lEMoN aUGH for SeeeEEEEEE`,
    `i just overall dont like spam cause of how salty it is`,
    `funny imaghe me || when funny teh funny hello https://cdn.discordapp.com/attachments/337470134950297602/801238072845926470/Gum-peppermint-720x720.png || <------- fUNNY!!Y!Y!Y!Y!`,
    `like for a sandwich or something savoury`,
    `this is the album cover for one of the artists i listen to`,
    `getting a and Mrs. tatoflower again feel Mr. and Mrs. Klein and their stuffed woofer puta. their stuffed have a`,
    `botto i am going to bread`,
    `BEPIS YES BEPIS ***YES*** BEPIS ED209 DICK JOESN ED 209 ** ROBOCOP I'LL BUY GARLICK FOR ** A BEPIS OCP FUTURE OF MODS ENFORCEMENT DICK JONES ROBOCOP **&YES***`,
    `of a friend of a friend of a || millioin || garlic`,
    `garlic garlic garlic garlic garlic garlic garlic garlic garlic garlic garlic garlic garlic bread`,
    `im ga||aaaaaaa||`,
    `WhO is BEpIs ** bruihj ** to the shane || eeeeeeeeeeeeeeeeeeeeeee || thjough ***yes*** to ** r ^&*`,
    `̻̦e͚͠ͅṉ ̬̼ͅe̛̹̟e͈̲̜n̝ ̠hó̼̠p̩̙̬ ͏͔̝t̼̜͠e͍̙̜ ̴̮g͕̪͢a̰̦̮a̺̳͔n̷͖̻,̭̺͢ ̷̳͙h͟i̞͓͢j͍̣̫ ̴̻͚K͔̻͢o̬̯̕n̤͇͡g̺͢!̗̺͈ ̕D̨̮̺K̺̖̩!͖̰͘ ̮c̙̯l͏̜̬ó͕̲w̹͟n̘̺̞ ̜̀ͅe͎͈̕n̞͕̲ s͙͔͜l̖ęch̹̪̰t̳͍̪e̤̖ͅ ͙s̪̺̹l̯͕̙e̺̪̠ch̩̞́t͏͙̪e̦̕ for me and my gf looks like the worst part`,
    `þÿ          þÿÿÿ  þÿÿÿ            What is 3 ||omanyte||`,
    `BEPIS PLZ TO ***HEMORRHAGE**`,
    `omanOMAN MICROWAVE IS SITRING ON TABLEE PLS TO HALP ***YES***`,
    `timespacecontinuunbreakomanomanOMANAAAAAA`,
    `OMANOMAN ITS GARLICBREAD aͪͧ͊eͦ́̈i͐͋̅o͛̄̑u̓ͯͩa̾ͣ͂eͤ̑ͫiͥ̽̇҉̨͕͝oͤ̓̓u̓̍ͬa͌̐̐êͭ̿i̒ͣͤoͦͩͤu͛̄̽aͦ̏ͭeͯͮ͌i̅̎ͨoͪ̾ͣu̍̆͒a̋̓ͨeͭ͗ͩi̓̍ͦö͑ͦȕͣͯã͐̓e͑͑̀iͫͥ̉ö́ͮͥu̇̂̓҉̹̰̲a̽̓̏ė̎̇iͥͬ͒҉̶̼̤oͭ̎͐üͫͫ҉̗͇͟å͒͛ë́͆̊҉̸͜͞i͋̒̑o͋͐̎u͋ͮ̅ä́̑͒e͋̄̏i͑ͥ̎óͬ̉u̅͆a҉eiouaei҉ouaeiouaeiouaeiouaeiou`,
    `R :poop:ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ`,
    `#NOOOOOOOOOOOOOOOOOOOO ** \n\n ||I NEED||`,
    `right:ok_hand::ok_hand: :ok_hand: :ok_hand::ok_hand: :ok_hand: :100: :ok_hand: :eyes: :eyes: :ok_hand::ok_hand: omaи`,
    `WN :clown:** POST THIS CLOWN :clown: POST ** THIS XO`,
    `ABSTAIN FROM BEANS`,
    `muddled with lime, with crushed ice and cacasa`,
    `using extendable arms such`,
    `location you search!   ***map***    `,
    `Need halp decide to simply not provide Internet access to the entire duration of the ** dollar ** :dollar: I am the big guy with the red sauce of the heretics afloweth ->>> || OaaaaaaaaaaaaaaaaOOOOOOO ||  `,
    `Maelys's cuddlner of a new problem to with the new update to it all up period delete last word no stop recording end recording stop Jimmy could you repreet, cant handle halo`,
    `at for her was limon :lemon::lemon::lemon::lemon::lemon::lemon:`,
    `O MAN IM NOT ** GOOD AT COMPUT ERS HALP ** O MAN I DON'''\'T generally specifically mostly`,
    `to the point gym game is at the To aid mobile users, I'll link small subreddits not yet in any cases, where the kernels dry out and become`,
    `GARLICCHARI! AND WHAT EVER ELSE YOU SIT ON SOMETIMES OR NOW>INTRAINNSIFY EDDITION  D̙̎̽I̓ͨ́S̺͙͒C̑͌ͭO͚ͯͯR̓̍̓D̾̉͌  Official Ohmawd -`,
    `** || ** || ** || BRUH || ** yesh ** !`
];

module.exports = markovData;